name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unitTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Run tests
        run: |
          npm ci
          npm test:ci
        env:
          CI: true
